######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 25 23:53:47 2012
######################################################################

TEMPLATE = app
TARGET = foo
DEPENDPATH += . ..
INCLUDEPATH += . ..
CONFIG += release
DESTDIR = .
QMAKE_LFLAGS = -static
LIBS += ../c3c.o

# Input
SOURCES += foo.cpp
